-- 'BTC', 'ETH', 'DASH', 'LTC', 'ETC', 'XRP', 'BCH', 'XMR', 'ZEC', 'QTUM', 'BTG', 'EOS'
CREATE TABLE `BTC_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `ETH_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `DASH_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `LTC_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `ETC_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `XRP_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `BCH_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `XMR_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `ZEC_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `QTUM_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `BTG_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `EOS_PRICE` (
	`DATE` DATETIME NULL DEFAULT NULL,
	`PRICE` VARCHAR(50) NULL DEFAULT NULL,
	INDEX `INDX_SEQ` (`DATE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
